# Generated by Django 5.0.2 on 2024-08-09 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_vendorlogin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packages',
            name='vendor',
        ),
    ]
