# Generated by Django 5.0.2 on 2024-08-09 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_remove_packages_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='vendor',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
